// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel fireworks_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x0010
};

AnimationCel fireworks_prologue_cel001[] = {
    /* Len */ 2,
    /* 000 */ 0x000c, 0xc19d, 0x1100,
    /* 001 */ 0x8014, 0x81dd, 0x0128
};

AnimationCel fireworks_prologue_cel002[] = {
    /* Len */ 4,
    /* 000 */ 0x000c, 0xc19d, 0x1100,
    /* 001 */ 0x8014, 0x81dd, 0x1128,
    /* 002 */ 0x0036, 0xc19d, 0x110a,
    /* 003 */ 0x0036, 0xc1dd, 0x0112
};

AnimationCel fireworks_prologue_cel003[] = {
    /* Len */ 1,
    /* 000 */ 0x80c0, 0xc000, 0x1008
};

AnimationCel fireworks_prologue_cel004[] = {
    /* Len */ 1,
    /* 000 */ 0x00c0, 0xc000, 0x1008
};

