// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel bon_dance_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x00dd
};

AnimationCel bon_dance_prologue_cel001[] = {
    /* Len */ 2,
    /* 000 */ 0x00c8, 0xc1b0, 0x0160,
    /* 001 */ 0x00c8, 0xc1b8, 0x0161
};

AnimationCel bon_dance_prologue_cel002[] = {
    /* Len */ 6,
    /* 000 */ 0x00c8, 0xc1b0, 0x0160,
    /* 001 */ 0x00c8, 0xc1b8, 0x0161,
    /* 002 */ 0x00c8, 0xc1f8, 0x016a,
    /* 003 */ 0x00c8, 0xc020, 0x016f,
    /* 004 */ 0x00c0, 0xc1f8, 0x014a,
    /* 005 */ 0x80c0, 0x41f0, 0x0149
};

AnimationCel bon_dance_prologue_cel003[] = {
    /* Len */ 5,
    /* 000 */ 0x00c8, 0xc1b0, 0x0177,
    /* 001 */ 0x00c8, 0xc1b8, 0x0178,
    /* 002 */ 0x00c8, 0xc1f8, 0x0020,
    /* 003 */ 0x00c8, 0xc020, 0x0025,
    /* 004 */ 0x00c0, 0xc1f8, 0x0000
};

