// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel sneaky_spirits_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x000f
};

AnimationCel sneaky_spirits_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x00f2, 0x81a1, 0x1080
};

AnimationCel sneaky_spirits_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x00f2, 0x81a1, 0x1080,
    /* 001 */ 0x00f2, 0x81b7, 0x1084
};

AnimationCel sneaky_spirits_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x00f2, 0x81a1, 0x1080,
    /* 001 */ 0x00f2, 0x81b7, 0x1084,
    /* 002 */ 0x00f2, 0x81ce, 0x1088
};

AnimationCel sneaky_spirits_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x00f2, 0x81a1, 0x1080,
    /* 001 */ 0x00f2, 0x81b7, 0x1084,
    /* 002 */ 0x00f2, 0x81ce, 0x1088,
    /* 003 */ 0x00f2, 0x81e5, 0x10cc
};

AnimationCel sneaky_spirits_prologue_cel005[] = {
    /* Len */ 5,
    /* 000 */ 0x00f2, 0x81a1, 0x1080,
    /* 001 */ 0x00f2, 0x81b7, 0x1084,
    /* 002 */ 0x00f2, 0x81ce, 0x1088,
    /* 003 */ 0x00f2, 0x81e5, 0x10cc,
    /* 004 */ 0x00f2, 0x8004, 0x10d1
};

AnimationCel sneaky_spirits_prologue_cel006[] = {
    /* Len */ 6,
    /* 000 */ 0x00f2, 0x81a1, 0x1080,
    /* 001 */ 0x00f2, 0x81b7, 0x1084,
    /* 002 */ 0x00f2, 0x81ce, 0x1088,
    /* 003 */ 0x00f2, 0x81e5, 0x10cc,
    /* 004 */ 0x00f2, 0x8004, 0x10d1,
    /* 005 */ 0x00f2, 0x801e, 0x10d5
};

