// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel sneaky_spirits_2_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x000f
};

AnimationCel sneaky_spirits_2_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x00eb, 0x81a9, 0x1080
};

AnimationCel sneaky_spirits_2_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x80f9, 0x81e4, 0x109d
};

AnimationCel sneaky_spirits_2_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x00eb, 0x800b, 0x10d1,
    /* 002 */ 0x80f9, 0x81e4, 0x109d
};

AnimationCel sneaky_spirits_2_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x00eb, 0x81ec, 0x10cc,
    /* 002 */ 0x00eb, 0x800b, 0x10d1,
    /* 003 */ 0x80f9, 0x81e4, 0x109d
};

AnimationCel sneaky_spirits_2_prologue_cel005[] = {
    /* Len */ 5,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x00eb, 0x81bf, 0x1084,
    /* 002 */ 0x00eb, 0x81ec, 0x10cc,
    /* 003 */ 0x00eb, 0x800b, 0x10d1,
    /* 004 */ 0x80f9, 0x81e4, 0x109d
};

AnimationCel sneaky_spirits_2_prologue_cel006[] = {
    /* Len */ 6,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x00eb, 0x81bf, 0x1084,
    /* 002 */ 0x00eb, 0x81ec, 0x10cc,
    /* 003 */ 0x00eb, 0x800b, 0x10d1,
    /* 004 */ 0x00eb, 0x8025, 0x10d5,
    /* 005 */ 0x80f9, 0x81e4, 0x109d
};

AnimationCel sneaky_spirits_2_prologue_cel007[] = {
    /* Len */ 7,
    /* 000 */ 0x00eb, 0x81a9, 0x1080,
    /* 001 */ 0x00eb, 0x81bf, 0x1084,
    /* 002 */ 0x00eb, 0x81d6, 0x1088,
    /* 003 */ 0x00eb, 0x81ec, 0x10cc,
    /* 004 */ 0x00eb, 0x800b, 0x10d1,
    /* 005 */ 0x00eb, 0x8025, 0x10d5,
    /* 006 */ 0x80f9, 0x81e4, 0x109d
};

