// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel ninja_bodyguard_prologue_cel000[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x1000,
    /* 001 */ 0x00ac, 0xc006, 0x1008,
    /* 002 */ 0x00cd, 0xc1e2, 0x1012
};

AnimationCel ninja_bodyguard_prologue_cel001[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x2000,
    /* 001 */ 0x00ac, 0xc006, 0x2008,
    /* 002 */ 0x00cd, 0xc1e2, 0x2012
};

AnimationCel ninja_bodyguard_prologue_cel002[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x3000,
    /* 001 */ 0x00ac, 0xc006, 0x3008,
    /* 002 */ 0x00cd, 0xc1e2, 0x3012
};

AnimationCel ninja_bodyguard_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x4000,
    /* 001 */ 0x00ac, 0xc006, 0x4008,
    /* 002 */ 0x00cd, 0xc1e2, 0x4012
};

AnimationCel ninja_bodyguard_prologue_cel004[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x5000,
    /* 001 */ 0x00ac, 0xc006, 0x5008,
    /* 002 */ 0x00cd, 0xc1e2, 0x5012
};

AnimationCel ninja_bodyguard_prologue_cel005[] = {
    /* Len */ 3,
    /* 000 */ 0x00ac, 0xc1c6, 0x6000,
    /* 001 */ 0x00ac, 0xc006, 0x6008,
    /* 002 */ 0x00cd, 0xc1e2, 0x6012
};

