// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rhythm_tweezers_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x00dd, 0x801a, 0x4028,
    /* 001 */ 0x40e5, 0xc1da, 0x4040,
    /* 002 */ 0x00d5, 0x41fa, 0x4004,
    /* 003 */ 0x40d5, 0x81da, 0x4000
};

AnimationCel rhythm_tweezers_prologue_cel001[] = {
    /* Len */ 4,
    /* 000 */ 0x00dd, 0x801a, 0x1028,
    /* 001 */ 0x40e5, 0xc1da, 0x1040,
    /* 002 */ 0x00d5, 0x41fa, 0x1004,
    /* 003 */ 0x40d5, 0x81da, 0x1000
};

AnimationCel rhythm_tweezers_prologue_cel008[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x100e,
    /* 001 */ 0x4000, 0x8020, 0x1012
};

AnimationCel rhythm_tweezers_prologue_cel000[] = {
    /* Len */ 4,
    /* 000 */ 0x40d5, 0x81da, 0x0000,
    /* 001 */ 0x00d5, 0x41fa, 0x0004,
    /* 002 */ 0x40e5, 0xc1da, 0x0040,
    /* 003 */ 0x00dd, 0x801a, 0x0028
};

AnimationCel rhythm_tweezers_prologue_cel009[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x000e,
    /* 001 */ 0x4000, 0x8020, 0x0012
};

AnimationCel rhythm_tweezers_prologue_cel007[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x200e,
    /* 001 */ 0x4000, 0x8020, 0x2012
};

AnimationCel rhythm_tweezers_prologue_cel006[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x300e,
    /* 001 */ 0x4000, 0x8020, 0x3012
};

AnimationCel rhythm_tweezers_prologue_cel002[] = {
    /* Len */ 4,
    /* 000 */ 0x00dd, 0x801a, 0x2028,
    /* 001 */ 0x40e5, 0xc1da, 0x2040,
    /* 002 */ 0x00d5, 0x41fa, 0x2004,
    /* 003 */ 0x40d5, 0x81da, 0x2000
};

AnimationCel rhythm_tweezers_prologue_cel005[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x400e,
    /* 001 */ 0x4000, 0x8020, 0x4012
};

AnimationCel rhythm_tweezers_prologue_cel003[] = {
    /* Len */ 4,
    /* 000 */ 0x00dd, 0x801a, 0x3028,
    /* 001 */ 0x40e5, 0xc1da, 0x3040,
    /* 002 */ 0x00d5, 0x41fa, 0x3004,
    /* 003 */ 0x40d5, 0x81da, 0x3000
};

