// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rhythm_tweezers_prologue_cel004[] = {
    /* Len */ 5,
    /* 000 */ 0x40d6, 0x81d2, 0x4000,
    /* 001 */ 0x00d6, 0x41f2, 0x4004,
    /* 002 */ 0x80d6, 0x4032, 0x400c,
    /* 003 */ 0x40e8, 0xc1d2, 0x4040,
    /* 004 */ 0x00e0, 0x8012, 0x4028
};

AnimationCel rhythm_tweezers_prologue_cel001[] = {
    /* Len */ 5,
    /* 000 */ 0x40d6, 0x81d2, 0x1000,
    /* 001 */ 0x00d6, 0x41f2, 0x1004,
    /* 002 */ 0x80d6, 0x4032, 0x100c,
    /* 003 */ 0x40e8, 0xc1d2, 0x1040,
    /* 004 */ 0x00e0, 0x8012, 0x1028
};

AnimationCel rhythm_tweezers_prologue_cel008[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x100e,
    /* 001 */ 0x4000, 0x8020, 0x1012
};

AnimationCel rhythm_tweezers_prologue_cel000[] = {
    /* Len */ 5,
    /* 000 */ 0x40d6, 0x81d2, 0x0000,
    /* 001 */ 0x00d6, 0x41f2, 0x0004,
    /* 002 */ 0x80d6, 0x4032, 0x000c,
    /* 003 */ 0x40e8, 0xc1d2, 0x0040,
    /* 004 */ 0x00e0, 0x8012, 0x0028
};

AnimationCel rhythm_tweezers_prologue_cel009[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x000e,
    /* 001 */ 0x4000, 0x8020, 0x0012
};

AnimationCel rhythm_tweezers_prologue_cel007[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x200e,
    /* 001 */ 0x4000, 0x8020, 0x2012
};

AnimationCel rhythm_tweezers_prologue_cel006[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x300e,
    /* 001 */ 0x4000, 0x8020, 0x3012
};

AnimationCel rhythm_tweezers_prologue_cel002[] = {
    /* Len */ 5,
    /* 000 */ 0x40d6, 0x81d2, 0x2000,
    /* 001 */ 0x00d6, 0x41f2, 0x2004,
    /* 002 */ 0x80d6, 0x4032, 0x200c,
    /* 003 */ 0x40e8, 0xc1d2, 0x2040,
    /* 004 */ 0x00e0, 0x8012, 0x2028
};

AnimationCel rhythm_tweezers_prologue_cel005[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x400e,
    /* 001 */ 0x4000, 0x8020, 0x4012
};

AnimationCel rhythm_tweezers_prologue_cel003[] = {
    /* Len */ 5,
    /* 000 */ 0x40d6, 0x81d2, 0x3000,
    /* 001 */ 0x00d6, 0x41f2, 0x3004,
    /* 002 */ 0x80d6, 0x4032, 0x300c,
    /* 003 */ 0x40e8, 0xc1d2, 0x3040,
    /* 004 */ 0x00e0, 0x8012, 0x3028
};

