.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Long 6) - Script Entry Point

script script_drum_lesson_long_6_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_long_6_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_long_6, script_drum_lesson_long_6_entry



.section .rodata
@ Drum Lesson (Long 6) - Data

text D_08064874
    .ascii "Commenàπons lág oà∑ on en\n"
    .ascii "áQtait avec la derniáare leàπon.\n"
    .ascii "Dis-moi que c'est encore\n"
    .asciz "frais dans ta tàÆteáR!"
endtext


script D_0806489c
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


script D_08064ad0
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 3
return


text D_08064b30
    .ascii "Maintenant, changeons\n"
    .ascii "la deuxiáame moitiáQáR!\n"
    .ascii "Le rythme est un peu\n"
    .asciz "saccadáQ alors áQcoute bienáR!"
endtext


script D_08064b6c
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08064d70
    .ascii "Rajoutons des cymbales\n"
    .ascii "pour que àπa páate vraimentáR!\n"
    .ascii "C'est presque comme tout ág\n"
    .asciz "l'heure, ne t'inquiáate pasáR!"
endtext


script D_08064da4
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08064fd8
    .ascii "Maintenant, ajoutons\n"
    .ascii "quelques toms pour\n"
    .ascii "donner du pepsáR!\n"
    .asciz "On dáQchire toutáR!"
endtext


script D_08065010
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08065268
    .ascii "Derniáare áQtapeáR! Remplace\n"
    .ascii "le tom qu'on vient d'ajouter\n"
    .ascii "par un roulementáR! àªa sonne\n"
    .asciz "si bien que j'en fráQmisáR!"
endtext


script D_080652a8
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_ROLL
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_ROLL
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_ROLL
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08065500
    .ascii "\n"
    .ascii "Pour cette leàπon, on va\n"
    .ascii "reprendre exactement\n"
    .asciz "lág oà∑ on en áQtait."
endtext


text D_08065530
    .ascii "Je recommande vivement\n"
    .ascii "d'avoir termináQ le cours\n"
    .ascii "Å·áRAvancáQ 5áRÅ‚ avant\n"
    .asciz "d'entamer celui-ciáR!"
endtext


text D_08065564
    .ascii "\n"
    .ascii "Tu es pràÆtáR?\n"
    .asciz "OK, c'est partiáR!"

endtext



.section .script.main
@ Drum Lesson (Long 6) - Tables

struct D_08a43358
    .word D_08064ad0
    .word D_0806489c
    .word s_hakushu_solo_seqData
    .word D_08064874
endstruct

struct D_08a43368
    .word D_08064ad0
    .word D_08064b6c
    .word s_hakushu_solo_seqData
    .word D_08064b30
endstruct

struct D_08a43378
    .word D_08064ad0
    .word D_08064da4
    .word s_warai_little_seqData
    .word D_08064d70
endstruct

struct D_08a43388
    .word D_08064ad0
    .word D_08065010
    .word s_warai_seqData
    .word D_08064fd8
endstruct

struct D_08a43398
    .word D_08064ad0
    .word D_080652a8
    .word s_kansei_solo_seqData
    .word D_08065268
endstruct



@ Drum Lesson (Long 6) - Main Script

script script_drum_lesson_long_6_main
    set_tempo 110
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 0
    dms_event09 6
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08065500
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08065530
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08065564
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a43358
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43368
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43378
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43388
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a43398
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
