.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Hi-Tech 2) - Script Entry Point

script script_drum_lesson_hi_tech_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_hi_tech_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_hi_tech_2, script_drum_lesson_hi_tech_2_entry



.section .rodata
@ Drum Lesson (Hi-Tech 2) - Data

text D_08065f9c
    .ascii "Ne commenˆ¹ons pas trop\n"
    .ascii "compliqu‡Q. Voici de quoi\n"
    .ascii "se remettre dans le bain.\n"
    .asciz "Tu vas y arriver‡R!"
endtext


script D_08065fc4
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
return


script D_080661ec
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
return


text D_08066258
    .ascii "\n"
    .ascii "Maintenant on commence\n"
    .ascii "pour de vrai‡R! ‡Pcoute\n"
    .asciz "bien et suis-moi."
endtext


script D_08066294
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08066480
    .ascii "\n"
    .ascii "Ajoutons un peu de grosse\n"
    .ascii "caisse et de caisse claire‡R!\n"
    .asciz "Tu penses pouvoir y arriver‡R?"
endtext


script D_080664b0
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_080666c0
    .ascii "Rajoutons un coup de grosse\n"
    .ascii "caisse‡R! Je l'ai gliss‡Q ‡g un\n"
    .ascii "endroit tr‡as fourbe, h‡Qh‡Q.\n"
    .asciz "Fais de ton mieux‡R!"
endtext


script D_080666f0
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08066918
    .ascii "Encore un coup de\n"
    .ascii "grosse caisse, et un\n"
    .ascii "autre de caisse claire.\n"
    .asciz "Mets-y du cˆ¸ur‡R!"
endtext


script D_08066964
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08066ba4
    .ascii "Ajoute un autre coup de\n"
    .ascii "grosse caisse‡R! Reste\n"
    .ascii "concentr‡Q et frappe comme\n"
    .asciz "si ta vie en d‡Qpendait‡R!"
endtext


script D_08066bd4
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08066e20
    .ascii "Rajoutons un coup de\n"
    .ascii "cymbale sur la grosse caisse\n"
    .ascii "que tu viens d'ajouter‡R!\n"
    .asciz "N'abandonne pas‡R!"
endtext


script D_08066e6c
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    spawn_cue CUE_SPLASH
    rest 6
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_080670c4
    .ascii "OK, j'ai ajout‡Q un autre coup\n"
    .ascii "de caisse claire au pattern‡R!\n"
    .ascii "On s'approche du grand final‡R!\n"
    .asciz "Fais preuve de d‡Qtermination‡R!"
endtext


script D_0806710c
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    spawn_cue CUE_SPLASH
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08067370
    .ascii "Le voici‡R! Le dernier pattern‡R!\n"
    .ascii "Juste un coup de tom‡R!\n"
    .ascii "Sens le rythme traverser\n"
    .asciz "ton corps et ton ‡ume‡R!"
endtext


script D_080673c8
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
    spawn_cue CUE_KICK_L
    rest 3
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    spawn_cue CUE_SPLASH
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08067638
    .ascii "Ce dernier cours va te tester\n"
    .ascii "sur toutes les techniques\n"
    .ascii "que je t'ai apprises dans\n"
    .asciz "les leˆ¹ons pr‡Qc‡Qdentes‡R!\n"
endtext


text D_08067668
    .ascii "\n"
    .ascii "ˆ»a risque d'ˆ®tre tr‡as difficile\n"
    .ascii "si tu n'as pas r‡Qussi\n"
    .asciz "certaines d'entre elles‡R!"
endtext


text D_0806769c
    .ascii "\n"
    .ascii "Alors tu es prˆ®t‡R?\n"
    .asciz "C'est parti‡R!"
endtext



.section .script.main
@ Drum Lesson (Hi-Tech 2) - Tables

struct D_08a437b4
    .word D_080661ec
    .word D_08065fc4
    .word s_hakushu_solo_seqData
    .word D_08065f9c
endstruct

struct D_08a437c4
    .word D_080661ec
    .word D_08066294
    .word s_hakushu_solo_seqData
    .word D_08066258
endstruct

struct D_08a437d4
    .word D_080661ec
    .word D_080664b0
    .word s_warai_little_seqData
    .word D_08066480
endstruct

struct D_08a437e4
    .word D_080661ec
    .word D_080666f0
    .word s_warai_seqData
    .word D_080666c0
endstruct

struct D_08a437f4
    .word D_080661ec
    .word D_08066964
    .word s_kansei_solo_seqData
    .word D_08066918
endstruct

struct D_08a43804
    .word D_080661ec
    .word D_08066bd4
    .word s_kansei_seqData
    .word D_08066ba4
endstruct

struct D_08a43814
    .word D_080661ec
    .word D_08066e6c
    .word s_kansei_seqData
    .word D_08066e20
endstruct

struct D_08a43824
    .word D_080661ec
    .word D_0806710c
    .word s_kansei_seqData
    .word D_080670c4
endstruct

struct D_08a43834
    .word D_080661ec
    .word D_080673c8
    .word s_kansei_seqData
    .word D_08067370
endstruct



@ Drum Lesson (Hi-Tech 2) - Main Script

script script_drum_lesson_hi_tech_2_main
    set_tempo 110
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08067638
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08067668
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0806769c
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a437b4
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a437c4
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a437d4
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a437e4
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a437f4
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43804
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43814
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43824
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a43834
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
