// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel cat_machine_cel000[] = {
    /* Len */ 4,
    /* 000 */ 0x00f8, 0x41f8, 0x1112,
    /* 001 */ 0x40f8, 0x4008, 0x111a,
    /* 002 */ 0x4000, 0x4008, 0x113a,
    /* 003 */ 0x00f7, 0x000e, 0x011f
};

AnimationCel cat_machine_cel001[] = {
    /* Len */ 4,
    /* 000 */ 0x00f6, 0x41f8, 0x1112,
    /* 001 */ 0x40fa, 0x400a, 0x111a,
    /* 002 */ 0x4002, 0x4006, 0x113a,
    /* 003 */ 0x00f9, 0x0010, 0x011f
};

AnimationCel cat_machine_cel002[] = {
    /* Len */ 1,
    /* 000 */ 0x00e0, 0xc1e0, 0x1008
};

AnimationCel cat_machine_cel003[] = {
    /* Len */ 1,
    /* 000 */ 0x00e0, 0xc1e0, 0x1000
};

AnimationCel cat_machine_cel004[] = {
    /* Len */ 1,
    /* 000 */ 0x00e0, 0xc1e0, 0x1018
};

AnimationCel cat_machine_cel005[] = {
    /* Len */ 1,
    /* 000 */ 0x00e0, 0xc1e0, 0x1010
};

AnimationCel cat_machine_cel006[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41f8, 0x1114
};

AnimationCel cat_machine_cel007[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41f8, 0x2118
};

AnimationCel cat_machine_cel008[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41f8, 0x1116
};

AnimationCel cat_machine_cel009[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41f8, 0x2104
};

AnimationCel cat_machine_cel010[] = {
    /* Len */ 1,
    /* 000 */ 0x00e9, 0x41f4, 0x1106
};

AnimationCel cat_machine_cel011[] = {
    /* Len */ 1,
    /* 000 */ 0x00e9, 0x41f4, 0x2100
};

AnimationCel cat_machine_cel012[] = {
    /* Len */ 1,
    /* 000 */ 0x0009, 0x41fd, 0x110a
};

AnimationCel cat_machine_cel013[] = {
    /* Len */ 1,
    /* 000 */ 0x0009, 0x41fd, 0x210c
};

AnimationCel cat_machine_cel014[] = {
    /* Len */ 1,
    /* 000 */ 0x00fd, 0x41ed, 0x1110
};

AnimationCel cat_machine_cel015[] = {
    /* Len */ 1,
    /* 000 */ 0x00fd, 0x41ed, 0x210e
};

AnimationCel cat_machine_cel016[] = {
    /* Len */ 1,
    /* 000 */ 0x00f5, 0x4006, 0x1108
};

AnimationCel cat_machine_cel017[] = {
    /* Len */ 1,
    /* 000 */ 0x00f5, 0x4006, 0x2102
};

