// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel polyrhythm_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x0018
};

AnimationCel polyrhythm_prologue_cel001[] = {
    /* Len */ 3,
    /* 000 */ 0x00d0, 0xc1c0, 0x0000,
    /* 001 */ 0x00d0, 0xc000, 0x0008,
    /* 002 */ 0x00d0, 0xc040, 0x0010
};

